
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { ThemeProvider } from "./components/importer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  >
      <body className="w-full h-full  ">
        <Header />
        <ThemeProvider>

        {children}
        </ThemeProvider>

      <Footer/>

      </body>
    </html>
  );
}
