
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="w-full h-full" lang="en">
      <body className="w-full h-full flex flex-col items-center justify-between">
      <Header/>

{children}

        
        <Footer/>
</body>
            </html>
  );
}
